In [3]:
import numpy as np
#배열 덧셈
array1 =np.random.randint(1,10,size=4).reshape(2,2)
array2 =array1+2
print(array1)
print(array2)

[[6 9]
 [4 5]]
[[ 8 11]
 [ 6  7]]


In [5]:
import numpy as np 
array1 =np.arange(4).reshape(2,2)
array2=np.arange(2)
array3=array1+array2
print(array1)
print(array2)
print(array3)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [7]:
import numpy as np
#브로드캐스팅
array1=np.arange(0,8).reshape(2,4)
array2=np.arange(0,8).reshape(2,4)
array3=np.concatenate([array1,array2],axis=0)
array4=np.arange(0,4).reshape(4,1)

print(array1)
print(array2)
print(array3)
print(array4)
print(array3+array4)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [12]:
import numpy as np
#마스킹
array1=np.arange(16).reshape(4,4)
print(array1)
array2=array1<10
print(array2)
array1[array2]=100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [14]:
import numpy as np 
array=np.arange(16).reshape(4,4)
print(np.max(array))
print(np.max(array))
print(np.sum(array,axis=1))

15
15
[ 6 22 38 54]


In [1]:
import numpy asnp


SyntaxError: invalid syntax (<ipython-input-1-912b1ddb80bd>, line 1)