In [1]:
import numpy as np 
array =np.arange(0,10)
np.save('saved.npy',array)

In [5]:
result =np.load('saved.npy')
print(result)
array1 =np.arange(0,10)
array2=np.arange(10,20)
np.savez('saved.npz',array1=array1,array2=array2)

data =np.load('saved.npz')
result1 =data['array1']
result2=data['array2']
print(result1)
print(result2)



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [6]:
import numpy as np
array=np.array([5,9,10,3,1])
array.sort()
print(array[::-1])


[10  9  5  3  1]


In [8]:
import numpy as np
array=np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)
array.sort(axis=1)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 1  3  5  9 10]
 [ 2  3  4  5  8]]


In [9]:
import numpy as np
array =np.linspace(0,10,5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
import numpy as np
print(np.random.randint(0,10,(2,3)))
array1=np.arange(0,10)
array2=np.copy(array1)
array2[0]=99
print(array1)
print(array2)


[[6 7 3]
 [5 3 0]]
[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]
