In [14]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [15]:
import numpy as np
list_data = [1,2,3]
array=np.array(list_data)
print(array.size)
print(array.dtype)
print(array[2])

3
int64
3


In [22]:
import numpy as np
#0부터 3까지의 배열 만들기
array1=np.arange(4)
print(array1)
array2=np.zeros((4,4),dtype=float)
print(array2)
array3=np.ones((3,3),dtype=int)
print(array3)
array4=np.random.randint(0,10,(3,3))
print(array4)
#평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5= np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[8 9 1]
 [4 5 6]
 [1 7 2]]
[[ 0.4580125   1.21689438 -1.0686097 ]
 [-0.12169585 -0.34788331  0.27167563]
 [-0.39377637 -0.76062375 -0.3661553 ]]


In [23]:
import numpy as np
#배열 연결하기
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3)
print(array3.size)



[1 2 3 4 5 6]
6


In [24]:
import numpy as np
#배열 모양바꾸기
array1 = np.array([1,2,3,4])
array2 =array1.reshape((2,2))

print(array2)

[[1 2]
 [3 4]]


In [29]:
import numpy as np
#배열 위로 연결하기
array1 =np.arange(4).reshape(1,4)
array2=np.arange(8).reshape(2,4)
print(array1)
print(array2)
array3 = np.concatenate([array1,array2],axis=0)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [34]:
import numpy as np 
#배열 가르기
array =np.arange(8).reshape(2,4)
left,right =np.split(array,[2],axis=1)
print(left.shape)
print(right.shape)
print(array)
print(left)
print(right)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
